CREATE TABLE `admin_system_settings` (
  `id` text PRIMARY KEY NOT NULL,
  `createdAt` integer NOT NULL,
  `updatedAt` integer NOT NULL,
  `updateCounter` integer NOT NULL DEFAULT 0,
  `stripePackStarter` text,
  `stripePackStandard` text,
  `stripePackBulk` text,
  `stripeSubMonthly` text,
  `stripeSubYearly` text,
  `enablePacks` integer NOT NULL DEFAULT 1,
  `enableSubscriptions` integer NOT NULL DEFAULT 1,
  `subsUnlimitedMode` text NOT NULL DEFAULT 'off',
  `subsUnlimitedAlsoGrantCredits` integer NOT NULL DEFAULT 0,
  `dailyFreeCreditsEnabled` integer NOT NULL DEFAULT 1,
  `dailyFreeCredits` integer NOT NULL DEFAULT 10,
  `dailyFreeReset` integer NOT NULL DEFAULT 0,
  `perUseCreditCost` integer NOT NULL DEFAULT 1,
  `guestDailyFreeEnabled` integer NOT NULL DEFAULT 1,
  `guestDailyFreeCredits` integer NOT NULL DEFAULT 10,
  `guestIpDailyLimit` integer NOT NULL DEFAULT 10,
  `guestDeviceDailyLimit` integer NOT NULL DEFAULT 100,
  `guestIpDailyCap` integer NOT NULL DEFAULT 20,
  `featureDashboardHome` integer NOT NULL DEFAULT 1,
  `featureDashboardTeams` integer NOT NULL DEFAULT 1,
  `featureDashboardMarketplace` integer NOT NULL DEFAULT 1,
  `featureDashboardBilling` integer NOT NULL DEFAULT 1,
  `featureDashboardSettings` integer NOT NULL DEFAULT 1,
  `dashboardHomeRoute` text NOT NULL DEFAULT '/dashboard/billing'
);
--> statement-breakpoint
INSERT INTO `admin_system_settings` (
  `id`,
  `createdAt`,
  `updatedAt`,
  `updateCounter`,
  `stripePackStarter`,
  `stripePackStandard`,
  `stripePackBulk`,
  `stripeSubMonthly`,
  `stripeSubYearly`,
  `enablePacks`,
  `enableSubscriptions`,
  `subsUnlimitedMode`,
  `subsUnlimitedAlsoGrantCredits`,
  `dailyFreeCreditsEnabled`,
  `dailyFreeCredits`,
  `dailyFreeReset`,
  `perUseCreditCost`,
  `guestDailyFreeEnabled`,
  `guestDailyFreeCredits`,
  `guestIpDailyLimit`,
  `guestDeviceDailyLimit`,
  `guestIpDailyCap`,
  `featureDashboardHome`,
  `featureDashboardTeams`,
  `featureDashboardMarketplace`,
  `featureDashboardBilling`,
  `featureDashboardSettings`,
  `dashboardHomeRoute`
)
VALUES (
  'default',
  CAST(strftime('%s', 'now') AS INTEGER),
  CAST(strftime('%s', 'now') AS INTEGER),
  0,
  null,
  null,
  null,
  null,
  null,
  1,
  1,
  'off',
  0,
  1,
  10,
  0,
  1,
  1,
  10,
  10,
  100,
  20,
  1,
  1,
  1,
  1,
  1,
  '/dashboard/billing'
);
